version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:docker-entrypoint-initdb.
    ports:
      - "5432:5432"

  user-service:
    build: ./user-service
    command: flask run --host=0.0.0.0
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/user_db
    ports:
      - "5000:5000"
    depends_on:
      - postgres

volumes:
  postgres_data:
